### ISSUE TITLE
Batch azure-batch-cli-extensions shows unknown version

### ISSUE THREAD

**Issue by mifung** [Azure/azure-batch-cli-extensions#103]
While running a batch job command:
az batch job create --template sql_job_template.json --parameters job-params.json, 
a series of python file errors return.
/*****************************************
Unexpect element blobSource in template
Traceback (most recent call last):
  File "/opt/az/lib/python3.6/site-packages/knack/cli.py", line 206, in invoke
    cmd_result = self.invocation.execute(args)
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/commands/__init__.py", line 328, in execute
    raise ex
********************************************/

**Comment by bgklein** [comment]
Could you run az --version to get some version information? Our REST API recently had a breaking change where blobSource was renamed httpUrl. Replacing this in your template should mitigate your issue, but I would like to investigate this further as the CLI should have been non-breaking.

**Comment by mifung** [comment]
Yes, the az- v returns the following:

Extensions:
azure-batch-cli-extensions             Unknown

Python location '/opt/az/bin/python3'
Extensions directory '/home/michael/.azure/cliextensions'

Python (Linux) 3.6.5 (default, Feb 21 2019, 23:58:07)
[GCC 5.4.0 20160609]

Legal docs and information: aka.ms/AzureCliLegal


Your CLI is up-to-date.

**Comment by bgklein** [comment]
It looks like there is a piece of validation code which is raising this error when it doesn't need to. I will update the SDK to fix this.

To mitigate the error immediately you should be able to replace blobSource with httpUrl in the file with no other changes necessary.  You could also downgrade to CLI v 2.0.58 and its respective version of the extension which should still use the old REST API.

**Comment by bgklein** [comment]
Could you try reinstalling the Batch CLI Extension? It looks like we have already added some code which should address this.
