### ISSUE TITLE
Task factory taskPerFile storing source files with owner root for absolute paths 

### ISSUE THREAD

**Issue by tojozefi** [Azure/azure-batch-cli-extensions#120]
When trying to download files from the source container of "taskPerFile" task factory to an absolute path in the filesystem, e.g. to a data disk mount /datadisk:
    "job":{
        "type":"Microsoft.Batch/batchAccounts/jobs",
        "properties":{
            "id":"[parameters('jobName')]",
            "onAllTasksComplete":"terminateJob",
            "poolInfo": {
                "poolId": "[parameters('poolId')]"
            },
            "taskFactory":{
                "type":"taskPerFile",
                "source":{
                    "fileGroup": "[parameters('inputFilegroup')]"
                },
                "repeatTask":{
                    "displayName":"Process file {fileName}",
                    "resourceFiles": [
                        {
                            "httpUrl": "{url}",
                            **"filePath": "/datadisk/[parameters('jobName')]/{fileName}"**
                        }, (…)
files (and directories in the path) are created with root owner, making it impossible for the tasks to access them:
# ls -l /datadisk
total 58343588
drwxrwxrwx  7 root     root               4096 Apr  9 12:49 ./
drwxr-xr-x 24 root     root               4096 Apr  9 11:45 ../
drwxr-x---  2 **root     root**               4096 Apr  9 12:40 dummyjob/

# ls -l /datadisk/dummyjob
total 58343588
drwxrwxrwx  7 root     root               4096 Apr  9 12:49 ./
drwxr-xr-x 24 root     root               4096 Apr  9 11:45 ../
-rwxrwx---  1 **root     root**                  9 Apr  9 12:25 dummyfile*

**Comment by bgklein** [comment]
Hi Tomasz, thank you for reporting this.  I will follow-up with you internally as I don't believe filePath supports absolute paths, so don't believe we are the ones placing the file in /datadisk

**Comment by tojozefi** [comment]
Closing due to conclusion that absolute paths are not supported for resource file paths.
