### ISSUE TITLE
Exit code does not distinguish successful job creation from failure

### ISSUE THREAD

**Issue by itowlson** [Azure/azure-batch-cli-extensions#19]
1. Create a job template with an **int** parameter.
2. Create a parameters file which sets that parameter to "weeble".
3. Run `az batch job create` with this template and parameters file.

Expected result: the command exits with a nonzero exit code, allowing a batch file, shell script or other programmatic consumer to detect failure.

Actual result: the command exits with exit code 0.  In addition, consumers cannot use stderr to detect failure, because the extensions write their "experimental feature" warnings to stderr regardless of whether the tool succeeds or not.

As we can only invoke the extension features via the CLI, not by calling the SDK directly, it would be really useful to be able to clearly distinguish success and failure and report the appropriate messages for each.

**Comment by annatisch** [comment]
I'm unable to reproduce this - each failed template gives me a 1 exit code. It's possible this has changed with an update to the CLI core - can you confirm whether it's still an issue for you?

**Comment by itowlson** [comment]
Still happening for me after running `az component update`.  Versions are azure-cli 2.0.10, batch 3.0.3 and batch-extensions 1.0.0rc3.  Here are my files:

**typetest.jobtemplate.json**

```
{
    "parameters": {
        "id": {
            "type": "string"
        },
        "p": {
            "type": "int"
        }
    },
    "job": {
        "type": "Microsoft.Batch/batchAccounts/jobs",
        "apiVersion": "2017-05-01.5.0",
        "properties": {
            "id": "[parameters('id')]",
            "poolInfo": {
                "poolId": "baaaaaaah"
            },
            "priority": "[parameters('p')]"
        }
    }
}
```

**parameters.json**

```
{
  "id" : "bibblingjob",
  "p" : "biscotti"
}
```

Code to run the command line:

```
> let p = Process.Start("az", "batch job create --template typetest.jobtemplate.json --parameters parameters.json >stdout.txt 2>stderr.txt");;
val p : Process = System.Diagnostics.Process (cmd)

> p.ExitCode;;
val it : int = 0
```

Contents of stderr.txt:

```
WARNING: You are using an experimental feature {Job Template}.
ERROR: Value 'biscotti' for parameter 'p' must be a int.
```

**Comment by itowlson** [comment]
Incidentally for my first attempt I forgot a colon and so my template was actually malformed JSON.  And I still got exit code 0...

**Comment by annatisch** [comment]
hmm thanks for trying again @itowlson - I will do some more tests.

**Comment by xingwu1** [comment]
No repro:

d:\github>az batch job create --template bad.json
ValueError: xxxx

d:\github>echo %errorlevel%
1
