### ISSUE TITLE
pool json file should take ssh pub-key not priv-key

### ISSUE THREAD

**Issue by kim0** [Azure/azure-batch-cli-extensions#28]
The json file that creates an azure batch pool, asks to take a user's ssh private key, while it should take a public key (servers always get public keys, and the private key doesn't leave my laptop). You can see the offending line here

https://github.com/Azure/vscode-azure-batch-tools/blob/master/schema/pool.schema.json#L626

**Comment by annatisch** [comment]
Thanks @kim0,
There's actually two different scenarios here. When creating a user account with which to remotely access the compute node, you're quite right and the server should be supplied with the public key. This is documented in the user create command:
[docs.microsoft.com/cli/azure/batch/node/user#create](https://docs.microsoft.com/en-us/cli/azure/batch/node/user#create)

The Linux user config on the pool that requires the private key is for a different scenario where the Batch service impersonates / runs a work load as a specified user. This concept is discussed further in this article:
[docs.microsoft.com/azure/batch/batch-user-accounts](https://docs.microsoft.com/en-us/azure/batch/batch-user-accounts)

Additionally, the specific scenario that requires the private ssh key is documented in the Batch API:
[docs.microsoft.com/rest/api/batchservice/add-a-pool-to-an-account#linuxUserConfiguration](https://docs.microsoft.com/en-us/rest/api/batchservice/add-a-pool-to-an-account#linuxUserConfiguration)

`The SSH private key is used to automatically configure password-less SSH between nodes in a Linux pool when the pool's enableInterNodeCommunication property is true. If not specified, password-less SSH is not configured between nodes.`

Hopefully this helps clarify :)

**Comment by kim0** [comment]
Thank you! It certainly helps. However can you please show me where to inject the public ssh key into the json file (that's used in --json-file)? The json schema did not mention any public ssh key :)

Thanks a lot

**Comment by annatisch** [comment]
The public ssh key is not actually part of pool create process. The `userAccounts` property on the pool is only for this "user impersonation" feature -  so the public key can't be inserted into this particular json file. You can however supply it in a json file to the user create command. Where your json will look like this:
```
{
    "name":"myuseraccount1",
    "isAdmin":true,  
    "password":"mypassword",  
    "expiryTime": "2017-08-01T23:00:00.000Z",
    "sshPublicKey": "mysshkey"
} 
```

This can then be added with an additional command:
```
az batch pool create --json-file my_pool.json
az batch node user create --pool-id <pool_id> --node-id <node_id> --json-file my_user_settings.json
```

**Comment by kim0** [comment]
Thank you, very useful info! So, the GUI (Azure portal), allows me to create a pool, create a user on that pool (on all nodes), put some code for pool-start-task, and run that start task under the user account I just created.

Can you please guide me how to achieve this with minimal number of steps / json files
PS: I also opened https://github.com/Azure/azure-batch-cli-extensions/issues/30 but it seems that user account in json is not for running tasks :(

**Comment by kim0** [comment]
Alright, since this bug report does not seem related to what I'm trying to do, I'm not very passionate about it :) I'll continue my discussion in https://github.com/Azure/azure-batch-cli-extensions/issues/30

However, thinking about it. It's a bit confusing to have user accounts in two different places. I mean, we could always be creating the user account using the same json file. And if the user should be remotely accessible, I'd supply public ssh key. If the user account would only be used to internally ssh'ing between nodes. I'd supply the private key. I can even supply both keys and the user-account ends up being used in both ways. That way seems more logical to me! 

Feel free to close this ticket at any time folks. Thanks

**Comment by annatisch** [comment]
Thanks @kim0 - I agree it's confusing to differentiate between the two scenarios that are both documented as a "user account" - even though they achieve very different things.... I'll give this feedback to the team.
