### ISSUE TITLE
pool list -o json cannot be used for pool create --json-file

### ISSUE THREAD

**Issue by kim0** [Azure/azure-batch-cli-extensions#29]
Dumping an existing pool into json format using `pool list -o json`, cannot later be imported into `pool create --json-file`. The reason being, the serialized json contains `nodeAgentSkuId` while the correct letter-case is `nodeAgentSKUId` (KU capitalized now). 

As you can imagine, some hair pulling was involved :)

Perhaps a unit test for that would be useful

**Comment by darylmsft** [comment]
The difference in capitalization is a concern and we will chase that down.

However, the flow you are attempting is not a feature of batch (extensions).  The entities returned by GETs can and do diverge from those required by PUTs.  Some fixups (by vi or other) can be expected.

**Comment by kim0** [comment]
Thanks, while I agree that GETs have many extra entities, I'm hoping they will be ignored when PUTing. This is the behavior I'm used to from kubernetes and it sort of makes sense. Thanks team for the fast replies!

**Comment by annatisch** [comment]
Thanks @kim0 - this capitalization conversion seems to be happening in the CLI core - I have posted an issue there:
https://github.com/Azure/azure-cli/issues/4061

**Comment by xingwu1** [comment]
This issue should be fixed with latest cli.

**Comment by xingwu1** [comment]
It wasn't solved

**Comment by xingwu1** [comment]
Fixed with azure-batch-extension 3.0.0
