### ISSUE TITLE
unable to use commonResourceFiles in a multiinstance task

### ISSUE THREAD

**Issue by xpillons** [Azure/azure-batch-cli-extensions#32]
When using a commonResourceFiles with a file group inside a multi-instance task as per this sample https://github.com/Azure/azure-batch-cli-extensions/blob/master/samples/mpi/job.json
I’m getting this error :
Malformed ResourceFile: Must have either  'source' or 'blobSource'

If I remove the commonResourceFiles, my job get submitted. So what is wrong here ?
[xhpl-job.json.txt](https://github.com/Azure/azure-batch-cli-extensions/files/1260388/xhpl-job.json.txt)

**Comment by xingwu1** [comment]
This issue has been resolved.
