### ISSUE TITLE
Release is incompatible with CLI core version 2.0.24

### ISSUE THREAD

**Issue by hmeiland** [Azure/azure-batch-cli-extensions#42]
2.0.22 and 2.0.23 of az-cli are good; 2.0.24 does not work any more with https://github.com/Azure/azure-batch-cli-extensions/releases/download/azure-batch-cli-extensions-2.0.1/azure_batch_cli_extensions-2.0.1-py2.py3-none-any.whl

Unable to load extension 'azure-batch-cli-extensions'. Use --debug for more information.
debug points to : ModuleNotFoundError: No module named 'azure.cli.core.help_files'

**Comment by darylmsft** [comment]
An update was released yesterday.  Can you please try azure-batch-cli-extensions 2.1.0?

d

**Comment by hmeiland** [comment]
yes, works for me with: 
az extension add --source https://github.com/Azure/azure-batch-cli-extensions/releases/download/azure-batch-cli-extensions-2.1.0/azure_batch_cli_extensions-2.1.0-py2.py3-none-any.whl

thank you!
