### ISSUE TITLE
Automatic insertion of cmd /c in task command lines

### ISSUE THREAD

**Issue by dkreg** [Azure/azure-batch-cli-extensions#43]
I've run into a couple of issues with the 'command prefixing' functions ( _add_cmd_prefix(), _is_prefixed(), etc.) used by _template_utils.py.

1. For job preparation tasks at least, if the commandLine template variable does not begin with the string cmd /c, then the CLI returns with the error 'Unknown pool OS flavor: None'. It appears that os_flavor isn't always being set, and this problem is exposed by the python functions pertaining to the command prefix.

2. I would like to use a commandLine value that doesn't invoke cmd.exe, but the command prefixing code in _template_utils.py unconditionally inserts cmd /c (and strips any other command line invocation, such as the useful cmd /s /c) . In particular, I'm trying to use the AzCopy command like so:

`"%ProgramFiles(x86)%/Microsoft SDKs/Azure/AzCopy/AzCopy" /S /Source:"https://containerURL" /Dest:. /SourceSAS:"?SASToken"`

This works fine as is, but I can't for the life of me get it to work when it is prepended with 'cmd /c'. The environment variable %ProgramFiles(x86)% contains spaces that cause the AzCopy path to be interpreted as 'C:\Program' rather than 'C:\Program Files (x86)\Microsoft SDKs...', _but only when either the /Source or/SourceSAS values are wrapped in quotes_.

A solution would be to remove all "" pairs except for the one enclosing the copy command. Unfortunately, the SourceSAS value contains '&' characters, and so must be enclosed in double quotes. The only workaround I've found, other than modifying the _add_cmd_prefix() function, is to put "%ProgramFiles(x86)%/Microsoft SDKs/Azure/AzCopy/AzCopy" into a .bat file, and execute that instead, but it's not ideal. Perhaps it isn't necessary to hardcode the cmd /c prefix into the az cli?

**Update:** `cmd /c setlocal ENABLEDELAYEDEXPANSION & "%ProgramFiles(x86)%/Microsoft SDKs/Azure/AzCopy/AzCopy" ...` fixes the problem.

**Comment by xingwu1** [comment]
@dkreg '

@dkreg Thank you for feedback:

for issue 1: this is our internal design, we have this issue when we couldn't find the platform type from simple pool name. We will continue to see how much we can do on this scenario.

for issue 2: I tested the following template:

{
    "parameters": {
        "jobId": {
            "type": "string",
            "metadata": {
                "description": "The id of Azure Batch job"
            }
        }
    },
    "job": {
        "type": "Microsoft.Batch/batchAccounts/jobs",
        "apiVersion": "2016-12-01",
        "properties": {
            "id": "[parameters('jobId')]",
            "constraints": {
                "maxWallClockTime": "PT5H",
                "maxTaskRetryCount": 1
            },
            "poolInfo": {
                "poolId": "winpool"
            },
            "taskFactory": {
                "type": "taskCollection",
                "tasks": [
                   {
                    "commandLine": "\"%ProgramFiles(x86)%/Microsoft SDKs/Azure/AzCopy/AzCopy\" /S /Source:\"https://containerURL\" /Dest:. /SourceSAS:\"?SASToken\"",
                    "id": "task1"
                    }
                ]
            }
        }
    }
}

Everything runs fine. Could you post your template?
