### ISSUE TITLE
Small inconsistency when using escape characters in CLI templates

### ISSUE THREAD

**Issue by dkreg** [Azure/azure-batch-cli-extensions#44]
In the JSON template file, \\" is used to escape double quotes in string values, but in the JSON file containing the values of the template parameters, double quotes must be escaped using \\\\\\". Presumably, commands such as `az batch job create --template job.json --parameters params.json` cause values in params.json to be processed twice.

**Comment by xingwu1** [comment]
Fixed with azure-batch-extension 3.0.0
