### ISSUE TITLE
poolEndpointConfiguration does not create inbound_nat_pool

### ISSUE THREAD

**Issue by skertz** [Azure/azure-batch-cli-extensions#46]
While using the Azure CLI v2 and the extensions with a --template and --json file to create an Azure Batch Pool, I found that the cli would report and error that poolEndpointConfiguration.inbound_nat_pool could not be none. This was because my code did not use "pool". Which is how the GUI (Portal) generates it when I perform a "az batch pool show"

            "networkConfiguration": {
                "endpointConfiguration": {
                    "inboundNatPools": [

The GUI would successfully add the inbound nat rule to the load balancer.

The only way I could successfully run a "az batch pool create --template --json-file" command was if my json contained the "poolEndpointConfiguration" as below. The command would succeed, but NO nat rule would be created on the load balancer. Only the default 3 rules per compute nodes.

            "networkConfiguration": {
                "poolendpointConfiguration": {
                    "inboundNatPools": [

**Comment by xingwu1** [comment]
@skertz Look into this issue. It would be nice if you can provide the repro template and the command you were using.

**Comment by xingwu1** [comment]
@skertz I used latest cli and extension(2.1), here is the template I am using:

```
{
    "pool": {
        "type": "Microsoft.Batch/batchAccounts/pools",
        "apiVersion": "2016-12-01",
        "properties": {
          "id": "pool2",
          "vmSize": "standard_a1",
          "virtualMachineConfiguration": {
            "imageReference": {
              "publisher": "Canonical",
              "offer": "UbuntuServer",
              "sku": "16.04.0-LTS"
            },
            "nodeAgentSKUId": "batch.node.ubuntu 16.04"
          },
          "networkConfiguration": {
            "endpointConfiguration": {
              "inboundNATPools": [ 
                  {
                    "name": "1234",
                    "protocol": "tcp",
                    "frontendPortRangeStart":60000,
                    "frontendPortRangeEnd":60051,
                    "backendPort": 1234
                  }
              ]
            }
          },
          "resizeTimeout": "PT15M",
          "targetDedicatedNodes": 5,
          "targetLowPriorityNodes": 0,
          "maxTasksPerNode": 3,
          "taskSchedulingPolicy": {
            "nodeFillType": "spread"
          },
          "enableAutoScale": false,
          "enableInterNodeCommunication": true
        }
    }
}
```
the command to use: 
```
az batch pool create --template pool.json
```
Everything run fine.

**Comment by xingwu1** [comment]
@skertz please re-open the issue if you can still repro the bug. Please attach the repro template. Thanks.
