### ISSUE TITLE
Ignored code blocks?

### ISSUE THREAD

**Issue by whatsondoc** [Azure/azure-batch-cli-extensions#58]
It appears as though certain blocks of code are being ignored if they fall outside of a property definition, without returning any errors or warnings.

Case in point is here: https://github.com/whatsondoc/azure-batch/blob/master/pool/marketplace-image/batch-pool-MP-fixed.azuredeploy.json

...where the pool startTask doesn't get applied as the pool Properties: property is closed (inadvertently, in this case) before the startTask is defined.

Can we add a validation to track/capture such scenarios, and (at least) report them as a warning on the CLI when deploying using templates?

**Comment by xingwu1** [comment]
Fixed with azure-batch-extension 3.0.0
