### ISSUE TITLE
support configuration variables. 

### ISSUE THREAD

**Issue by matthew-rollitt** [Azure/azure-batch-cli-extensions#67]
[variables('environmentSettings')[parameters('environmentName')].instanceSize]

"parameters": {
    "environmentName": {
        "type": "string",
        "allowedValues": [
          "test",
          "prod"
        ]
    }
},
"variables": {
    "environmentSet": {
        "test": {
            "instanceSize": "Small",
            "instanceCount": 1
        },
        "prod": {
            "instanceSize": "Large",
            "instanceCount": 4
        }
    }
},
https://docs.microsoft.com/en-us/azure/azure-resource-manager/resource-manager-templates-variables

as discussed in an email thread configuration variables don't work since the array slices the first two characters off \\'nvironmentSet)[test].instanceSi\\''”

**Comment by matthew-rollitt** [comment]
just tested out these changes. Looks like it can't handle [variables('environmentTab')[parameters('environmentName')].instanceSize] correctly and it's ingnoring the last two characters at the end of the array. I'm seeing the following error message

Template contains no definition for variable \\'environmentTab\\')[parameters(\\'environmentName\\')].instanceSi\\'

**Comment by xingwu1** [comment]
Fixed with azure-batch-extension 3.0.0
