### ISSUE TITLE
az batch pool create command isn't running as expected.

### ISSUE THREAD

**Issue by malhmoud-MSFT** [Azure/azure-batch-cli-extensions#82]
Hi,
I tried running az batch pool create --template pool.json, but what I get in return is
"az: error: unrecognized arguments: --template pool.json",
Has the CLI version been updated and this article wasn't?
my pool.json file has the following:
"pool": {
"type": "Microsoft.Batch/batchAccounts/pools",
"apiVersion": "2016-12-01",
"properties": {
"id": "helloworld-pool",
"cloudServiceConfiguration": {
"osFamily": "4",
"targetOSVersion": "*"
},
"vmSize": "small",
"targetDedicatedNodes": 1
}
}
}
my az batch cli version is 3.3.0
Detailed error under --debug:
Command arguments: ['batch', 'pool', 'create', '--template', 'pool.json', '--debug']
Event: Cli.PreExecute []
Event: CommandParser.OnGlobalArgumentsCreate [<function CLILogging.on_global_arguments at 0x03F02E40>, <function OutputProducer.on_global_arguments at 0x0443EA98>, <function CLIQuery.on_global_arguments at 0x04226468>]
Event: CommandInvoker.OnPreCommandTableCreate [<function CLILogging.remove_logger_flags at 0x03F02E88>]
Installed command modules ['acr', 'acs', 'advisor', 'ams', 'appservice', 'backup', 'batch', 'batchai', 'billing', 'cdn', 'cloud', 'cognitiveservices', 'configure', 'consumption', 'container', 'cosmosdb', 'dla', 'dls', 'dms', 'eventgrid', 'eventhubs', 'extension', 'feedback', 'find', 'interactive', 'iot', 'keyvault', 'lab', 'maps', 'monitor', 'network', 'policyinsights', 'profile', 'rdbms', 'redis', 'reservations', 'resource', 'role', 'servicebus', 'servicefabric', 'sql', 'storage', 'vm']
Loaded module 'acr' in 0.004 seconds.
Loaded module 'acs' in 0.004 seconds.
Loaded module 'advisor' in 0.002 seconds.
Event: CommandLoader.OnLoadCommandTable []
Loaded module 'ams' in 0.006 seconds.
Loaded module 'appservice' in 0.005 seconds.
Loaded module 'backup' in 0.003 seconds.
Event: CommandLoader.OnLoadCommandTable []
Loaded module 'batch' in 0.010 seconds.
Loaded module 'batchai' in 0.004 seconds.
Loaded module 'billing' in 0.002 seconds.
Event: CommandLoader.OnLoadCommandTable []
Loaded module 'cdn' in 0.003 seconds.
Loaded module 'cloud' in 0.002 seconds.
Loaded module 'cognitiveservices' in 0.002 seconds.
Loaded module 'configure' in 0.002 seconds.
Loaded module 'consumption' in 0.006 seconds.
Loaded module 'container' in 0.002 seconds.
Loaded module 'cosmosdb' in 0.004 seconds.
Loaded module 'dla' in 0.005 seconds.
Loaded module 'dls' in 0.004 seconds.
Loaded module 'dms' in 0.002 seconds.
Loaded module 'eventgrid' in 0.002 seconds.
Loaded module 'eventhubs' in 0.003 seconds.
Loaded module 'extension' in 0.002 seconds.
Loaded module 'feedback' in 0.001 seconds.
Loaded module 'find' in 0.001 seconds.
Loaded module 'interactive' in 0.001 seconds.
Loaded module 'iot' in 0.005 seconds.
Loaded module 'keyvault' in 0.005 seconds.
Loaded module 'lab' in 0.004 seconds.
Loaded module 'maps' in 0.002 seconds.
Loaded module 'monitor' in 0.006 seconds.
Loaded module 'network' in 0.019 seconds.
Loaded module 'policyinsights' in 0.003 seconds.
Loaded module 'profile' in 0.283 seconds.
Loaded module 'rdbms' in 0.004 seconds.
Loaded module 'redis' in 0.003 seconds.
Loaded module 'reservations' in 0.002 seconds.
Loaded module 'resource' in 0.014 seconds.
Loaded module 'role' in 0.003 seconds.
Loaded module 'servicebus' in 0.005 seconds.
Loaded module 'servicefabric' in 0.003 seconds.
Loaded module 'sql' in 0.006 seconds.
Event: CommandLoader.OnLoadCommandTable []
Loaded module 'storage' in 0.020 seconds.
Loaded module 'vm' in 0.011 seconds.
Loaded all modules in 0.477 seconds. (note: there's always an overhead with the first module loaded)
Extensions directory: 'C:\Users\malhmoud.azure\cliextensions'
Event: CommandInvoker.OnPreCommandTableTruncate []
Event: CommandLoader.OnLoadArguments []
Event: CommandInvoker.OnPostCommandTableCreate [<function add_id_parameters at 0x044060C0>, <function register_global_subscription_parameter..add_subscription_parameter at 0x044560C0>]
Event: CommandInvoker.OnCommandTableLoaded []
Event: CommandInvoker.OnPreParseArgs [<function _documentdb_deprecate at 0x04653DF8>]
az: error: unrecognized arguments: --template pool.json
usage: az [-h] [--verbose] [--debug] [--output {json,jsonc,table,tsv}]
[--query JMESPATH]
{batch} ...

**Comment by bgklein** [comment]
Could you confirm you have the batch-extensions module installed.  Steps can be found at https://github.com/Azure/azure-batch-cli-extensions#cli-extensions-installation .

**Comment by bgklein** [comment]
Issue is believed to be due to not having the cli-extensions module installed
