### ISSUE TITLE
Unable to get azure batch CLI extensions working on Windows

### ISSUE THREAD

**Issue by worldbeater** [Azure/azure-batch-cli-extensions#90]
Steps to reproduce:
1. Use a PC with latest Windows 10 installed
2. Install <a href="https://docs.microsoft.com/en-us/cli/azure/install-azure-cli-windows?view=azure-cli-latest#install-or-update">Azure CLI using Windows Installer</a>
3. Open <a href="https://github.com/Azure/azure-batch-cli-extensions">README.md</a> and try to install the package
4. Use `az extension add -n azure-batch-cli-extensions`. You get:
```
An error occurred. Pip failed with status code 1. Use --debug for more information.
```
5. Install latest <a href="https://www.python.org/">Python</a> binaries. Use `pip install azure-batch-extensions` You get:
```
azure-mgmt-storage 1.5.0 has requirement msrestazure~=0.4.11, but you'll have msrestazure 0.5.0 which is incompatible. 
azure-mgmt-batch 4.1.0 has requirement msrestazure~=0.4.7, but you'll have msrestazure 0.5.0 which is incompatible.
```

I am completely not sure if this tooling is correctly installed after all, but I'm unable to create a job from a JSON template after I log in using `az login`. If I type:
```
az batch job create --template sample.json --account-name myaccount --account-endpoint https://myaccount.northeurope.batch.azure.com
```
I get:
```
az: error: unrecognized arguments: --template sample.json
usage: az [-h] [--verbose] [--debug] [--output {json,jsonc,table,tsv,yaml}]
          [--query JMESPATH]
          {batch} ...
```

Need to mention that this extension works perfectly on my PC with Ubuntu 18.04 installed.

**Comment by xingwu1** [comment]
Looking into the issue.

**Comment by xingwu1** [comment]
The issue is due to Azure cli pin to specific version pycparser in Windows build. Working on a fix now.
