### ISSUE TITLE
Unable to install batch extension in azure cli docker image

### ISSUE THREAD

**Issue by gauravsaralMs** [Azure/azure-batch-cli-extensions#94]
Create a docker instance from 
https://hub.docker.com/r/microsoft/azure-cli/

Running `az extension add -n azure-batch-cli-extensions --debug` fails

**Comment by bgklein** [comment]
What is your error message

**Comment by gauravsaralMs** [comment]
few last lines from the install command when ran with debug
Command '['/usr/local/bin/python', '-m', 'pip', 'install', '--target', '/root/.azure/cliextensions/azure-batch-cli-extensions', '/tmp/tmpcsit3vpn/azure_batch_cli_extensions-2.5.1-py2.py3-none-any.whl', '-vv', '--disable-pip-version-check', '--no-cache-dir']' returned non-zero exit status 1.
Pip failed so deleting anything we might have installed at /root/.azure/cliextensions/azure-batch-cli-extensions
An error occurred. Pip failed with status code 1. Use --debug for more information.

**Comment by bgklein** [comment]
It looks like the following error occurs during the download of the cffi and cryptography dependencies. This is likely due to the minimized environment of the docker container. I was able to reproduce the issue, but have not had time to look for what packages need to be installed to the container to make it work.

**Comment by bgklein** [comment]
I have confirmed with the azure-cli team that this is an issue on the container end.

For a temporary mitigation you should be able to resolve the issue by running "apk add --no-cache --virtual .build-deps gcc make openssl-dev libffi-dev musl-dev && bash" in the container.
